services:
  postgres:
    container_name: threads_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: threads
      POSTGRES_DB: threads_db
      
volumes:
  postgres_data: